USE [master]
GO
/****** Object:  Database [GlobalCarSales]    Script Date: 12/09/2026 3:30:56 PM ******/
CREATE DATABASE [GlobalCarSales]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GlobalCarSales', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\GlobalCarSales.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GlobalCarSales_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\GlobalCarSales_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GlobalCarSales] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GlobalCarSales].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GlobalCarSales] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GlobalCarSales] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GlobalCarSales] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GlobalCarSales] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GlobalCarSales] SET ARITHABORT OFF 
GO
ALTER DATABASE [GlobalCarSales] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GlobalCarSales] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GlobalCarSales] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GlobalCarSales] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GlobalCarSales] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GlobalCarSales] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GlobalCarSales] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GlobalCarSales] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GlobalCarSales] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GlobalCarSales] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GlobalCarSales] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GlobalCarSales] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GlobalCarSales] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GlobalCarSales] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GlobalCarSales] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GlobalCarSales] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GlobalCarSales] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GlobalCarSales] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GlobalCarSales] SET  MULTI_USER 
GO
ALTER DATABASE [GlobalCarSales] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GlobalCarSales] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GlobalCarSales] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GlobalCarSales] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GlobalCarSales] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GlobalCarSales] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [GlobalCarSales] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GlobalCarSales] SET QUERY_STORE = ON
GO
ALTER DATABASE [GlobalCarSales] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GlobalCarSales]
GO
/****** Object:  Table [dbo].[Cars]    Script Date: 12/09/2026 3:30:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cars](
	[car_id] [int] NOT NULL,
	[company_id] [int] NOT NULL,
	[model] [varchar](100) NOT NULL,
	[category] [varchar](50) NOT NULL,
	[fuel_type] [varchar](50) NOT NULL,
	[model_year] [int] NULL,
	[price] [decimal](12, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[car_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Companies]    Script Date: 12/09/2026 3:30:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Companies](
	[company_id] [int] NOT NULL,
	[company_name] [varchar](100) NOT NULL,
	[headquarters_country] [varchar](100) NOT NULL,
	[founded_year] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[company_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Countries]    Script Date: 12/09/2026 3:30:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Countries](
	[country_id] [int] NOT NULL,
	[country_name] [varchar](100) NOT NULL,
	[region] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[country_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customers]    Script Date: 12/09/2026 3:30:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[customer_id] [int] NOT NULL,
	[customer_name] [varchar](150) NOT NULL,
	[gender] [varchar](20) NULL,
	[age] [int] NULL,
	[country_id] [int] NOT NULL,
	[email] [varchar](150) NULL,
	[phone] [varchar](50) NULL,
	[registration_date] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sales]    Script Date: 12/09/2026 3:30:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sales](
	[sale_id] [int] NOT NULL,
	[customer_id] [int] NOT NULL,
	[car_id] [int] NOT NULL,
	[sale_date] [date] NOT NULL,
	[quantity] [int] NOT NULL,
	[discount_percent] [decimal](5, 2) NULL,
	[final_price] [decimal](12, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[sale_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cars]  WITH NOCHECK ADD  CONSTRAINT [FK_Cars_Companies] FOREIGN KEY([company_id])
REFERENCES [dbo].[Companies] ([company_id])
GO
ALTER TABLE [dbo].[Cars] CHECK CONSTRAINT [FK_Cars_Companies]
GO
ALTER TABLE [dbo].[Customers]  WITH NOCHECK ADD  CONSTRAINT [FK_Customers_Countries] FOREIGN KEY([country_id])
REFERENCES [dbo].[Countries] ([country_id])
GO
ALTER TABLE [dbo].[Customers] CHECK CONSTRAINT [FK_Customers_Countries]
GO
ALTER TABLE [dbo].[Sales]  WITH NOCHECK ADD  CONSTRAINT [FK_Sales_Cars] FOREIGN KEY([car_id])
REFERENCES [dbo].[Cars] ([car_id])
GO
ALTER TABLE [dbo].[Sales] CHECK CONSTRAINT [FK_Sales_Cars]
GO
ALTER TABLE [dbo].[Sales]  WITH NOCHECK ADD  CONSTRAINT [FK_Sales_Customers] FOREIGN KEY([customer_id])
REFERENCES [dbo].[Customers] ([customer_id])
GO
ALTER TABLE [dbo].[Sales] CHECK CONSTRAINT [FK_Sales_Customers]
GO
USE [master]
GO
ALTER DATABASE [GlobalCarSales] SET  READ_WRITE 
GO
